name: check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Install, test and build
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - run: npm install
      - run: npm run prepublish
